const data = [
    ["Lith A1", "Braton Prime Barrel", "Forma Blueprint", "Vasto Prime Receiver", "Saryn Prime Neuroptics Blueprint", "Vectis Prime Blueprint", "Akstiletto Prime Blueprint"],
    ["Lith A3", "Lex Prime Blueprint", "Orthos Prime Handle", "Rubico Prime Receiver", "Akbolto Prime Barrel", "Tiberon Prime Blueprint", "Akjagara Prime Barrel"],
    ["Lith A4", "Forma Blueprint", "Burston Prime Receiver", "Corinth Prime Blueprint", "Baza Prime Barrel", "Ivara Prime Systems Blueprint", "Astilla Prime Barrel"],
    ["Lith A2", "Lex Prime Barrel", "Forma Blueprint", "Valkyr Prime Blueprint", "Akbronco Prime Link", "Cernos Prime Blueprint", "Akstiletto Prime Blueprint"],
    ["Lith B1", "Mag Prime Neuroptics Blueprint", "Ankyros Prime Blueprint", "Forma Blueprint", "Rhino Prime Neuroptics Blueprint", "Boltor Prime Receiver", "Boar Prime Stock"],
    ["Lith B2", "Forma Blueprint", "Paris Prime Lower Limb", "Tigris Prime Stock", "Braton Prime Receiver", "Orthos Prime Blade", "Ballistica Prime Blueprint"],
    ["Lith B3", "Burston Prime Blueprint", "Forma Blueprint", "Limbo Prime Systems Blueprint", "Cernos Prime String", "Orthos Prime Blade", "Ballistica Prime Blueprint"],
    ["Lith B4", "Ankyros Prime Blueprint", "Forma Blueprint", "Nyx Prime Blueprint", "Rhino Prime Neuroptics Blueprint", "Scindo Prime Blueprint", "Boltor Prime Blueprint"],
    ["Lith B5", "Oberon Prime Chassis Blueprint", "Lex Prime Receiver", "Banshee Prime Neuroptics Blueprint", "Rubico Prime Stock", "Orthos Prime Blade", "Ballistica Prime Blueprint"],
    ["Lith B6", "Fang Prime Blueprint", "Lex Prime Barrel", "Limbo Prime Systems Blueprint", "Orthos Prime Blueprint", "Redeemer Prime Blueprint", "Ballistica Prime Blueprint"],
    ["Lith B7", "Forma Blueprint", "Lex Prime Receiver", "Tipedo Prime Blueprint", "Aksomati Prime Barrel", "Orthos Prime Blueprint", "Baza Prime Blueprint"],
    ["Lith B8", "Aksomati Prime Blueprint", "Burston Prime Stock", "Dethcube Prime Systems", "Atlas Prime Chassis Blueprint", "Ivara Prime Blueprint", "Baza Prime Blueprint"],
    /* ["Lith C1", "", "", "", "", "", ""],
    ["Lith C2", "", "", "", "", "", ""],
    ["Lith C2", "", "", "", "", "", ""],
    ["Lith C5", "", "", "", "", "", ""],
    ["Lith C6", "", "", "", "", "", ""],
    ["Lith C7", "", "", "", "", "", ""],
    ["Lith C8", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["Lith B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""],
    ["B2", "", "", "", "", "", ""], */
]

module.exports.data = data